"""
do not edit this file!!
your code will not work
"""

from karel.stanfordkarel import *
import random

### extra functions ###
def turn_right():
    for i in range(3):
        turn_left()

### for problem 1 ###
def start():
    def move_n(n):
        for i in range(n):
            move()

    def put_n(n):
        for i in range(n):
            put_beeper()

    def put_some_each_row():
        rnd1, rnd2 = random.randint(1, 6), random.randint(1, 6)
        turn_left()
        move_n(rnd1)
        put_n(rnd2)
        turn_left(); turn_left()
        move_n(rnd1)
        turn_left()
        if front_is_clear():
            move()

    def put_many():
        turn_left()
        for i in range(6):
            move()
            if random.random() > 0.7:
                put_n(random.randint(1, 6))
        turn_left(); turn_left()
        move_n(6)
        turn_left()
        if front_is_clear():
            move()

    for i in range(7):
        #put_some_each_row()
        put_many()
    turn_left()
    world.setDelay(10)  # slider = 90
