"""
do not edit this file!!
your code will not work
"""

from karel.stanfordkarel import *
import random

### extra functions ###
def turn_right():
    for i in range(3):
        turn_left()


### for problem 2 ###

def start():

    def put_n(n):
        for i in range(n):
            put_beeper()
    
    beep_spot = sorted(random.sample(range(1,24), 7))  # where to put e.g.[3,5,8,15,19,21]
    step_count = 0
    for i in [4,4,4,3,3,2,2,1,1]:
        for j in range(i):
            move()
            step_count += 1 
            if step_count in beep_spot:
                put_n(random.randint(1,8))
        turn_left()
    world.setDelay(10)  # slider = 90
